<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sakshi" ignored="0" name="Test2" tests="2" failures="2" timestamp="27 Mar 2021 21:50:48 GMT" time="53.515" errors="0">
  <testcase name="veriftLoggedInUSerTest" time="3.574" classname="com.sanyam.testproject.HomePageTest">
    <failure type="java.lang.AssertionError" message="User was not able to login successfully expected [ Choudhary] but found [Sanyam Choudhary]">
      <![CDATA[java.lang.AssertionError: User was not able to login successfully expected [ Choudhary] but found [Sanyam Choudhary]
at com.sanyam.uipackage.HomePage.userLoggedIn(HomePage.java:28)
at com.sanyam.testproject.HomePageTest.veriftLoggedInUSerTest(HomePageTest.java:37)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- veriftLoggedInUSerTest -->
  <testcase name="veriftLoggedInUSerTest" time="3.584" classname="com.sanyam.testproject.HomePageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.sanyam.frameworkpackage.ExtentManager.getScreenshot(ExtentManager.java:48)
at com.sanyam.frameworkpackage.TestListners.onTestFailure(TestListners.java:48)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- veriftLoggedInUSerTest -->
</testsuite> <!-- Test2 -->
