<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="29447" started-at="2021-03-20T21:37:28Z" finished-at="2021-03-20T21:37:57Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="29447" started-at="2021-03-20T21:37:28Z" finished-at="2021-03-20T21:37:57Z">
      <class name="com.sanyam.testproject.TestDemo">
        <test-method status="PASS" signature="initAll()[pri:0, instance:com.sanyam.testproject.TestDemo@306279ee]" name="initAll" is-config="true" duration-ms="411" started-at="2021-03-20T21:37:28Z" finished-at="2021-03-20T21:37:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initAll -->
        <test-method status="PASS" signature="openBrowserUrl()[pri:0, instance:com.sanyam.testproject.TestDemo@306279ee]" name="openBrowserUrl" is-config="true" duration-ms="22012" started-at="2021-03-20T21:37:28Z" finished-at="2021-03-20T21:37:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowserUrl -->
        <test-method status="PASS" signature="LoginFreeCRM()[pri:0, instance:com.sanyam.testproject.TestDemo@306279ee]" name="LoginFreeCRM" duration-ms="742" started-at="2021-03-20T21:37:50Z" finished-at="2021-03-20T21:37:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFreeCRM -->
        <test-method status="FAIL" signature="testCase2()[pri:0, instance:com.sanyam.testproject.TestDemo@306279ee]" name="testCase2" duration-ms="5424" started-at="2021-03-20T21:37:51Z" finished-at="2021-03-20T21:37:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Test Fail 2-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Sun_Mar_21_03_07_56_IST_2021.png,
Test Fail 3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Test Fail 2-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Sun_Mar_21_03_07_56_IST_2021.png,
Test Fail 3
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.sanyam.testproject.TestDemo.testCase2(TestDemo.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method status="SKIP" signature="testSkip()[pri:0, instance:com.sanyam.testproject.TestDemo@306279ee]" name="testSkip" duration-ms="3" started-at="2021-03-20T21:37:57Z" finished-at="2021-03-20T21:37:57Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Testig Skip test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Testig Skip test
at com.sanyam.testproject.TestDemo.testSkip(TestDemo.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
        <test-method status="PASS" signature="testSuccess()[pri:0, instance:com.sanyam.testproject.TestDemo@306279ee]" name="testSuccess" duration-ms="2" started-at="2021-03-20T21:37:57Z" finished-at="2021-03-20T21:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccess -->
        <test-method status="PASS" signature="aftertest()[pri:0, instance:com.sanyam.testproject.TestDemo@306279ee]" name="aftertest" is-config="true" duration-ms="0" started-at="2021-03-20T21:37:57Z" finished-at="2021-03-20T21:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
      </class> <!-- com.sanyam.testproject.TestDemo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
